# docker-compose.yml
version: '3'

services:
    pdf-generator-apache:
        build:
            context: .
            dockerfile: .docker/Dockerfile-apache
        image: feegow-pdf-generator-apache
        container_name: pdf-generator-apache
        environment:
            - XDEBUG_MODE=debug
            - XDEBUG_CLIENT_HOST=host.docker.internal
            - XDEBUG_CLIENT_PORT=9003
            - XDEBUG_IDEKEY=PHPSTORM
        ports:
            - "8008:80"
        # comentar mapeamento de volume para produção
        volumes:
            - .:/var/www/html

#    pdf-generator-ngix:
#        build:
#            context: .
#            dockerfile: .docker/Dockerfile-nginx
#        image: feegow-pdf-generator-nginx
#        container_name: pdf-generator-nginx
#        environment:
#            - XDEBUG_MODE=debug
#            - XDEBUG_CLIENT_HOST=host.docker.internal
#            - XDEBUG_CLIENT_PORT=9003
#            - XDEBUG_IDEKEY=PHPSTORM
#        ports:
#            - "8009:80"
#        # comentar mapeamento de volume para produção
#        volumes:
#            - .:/var/www/html
