# .docker/Dockerfile-nginx
FROM php:8.2-fpm-bullseye

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=America/Sao_Paulo

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Instalação de dependências e extensões do PHP
RUN apt-get update && apt-get install -y \
    gnupg \
    curl \
    ca-certificates \
    zip \
    unzip \
    git \
    supervisor \
    sqlite3 \
    libpng-dev \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libxml2-dev \
    libxrender1 \
    default-mysql-client \
    nginx \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql zip bcmath soap intl
#    && pecl install redis xdebug \
#    && docker-php-ext-enable redis xdebug

# Instalação do Node.js v20 e Puppeteer
RUN apt-get update && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs \
    && npm install puppeteer --global

# Instalação do Composer
RUN curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# wkhtmltopdf
ENV WKTHMLTOPDF_DISTRO_VERSION bullseye
ENV WKTHMLTOPDF_VERSION 0.12.6.1-2
ENV WKHTMLTOPDX_FILE wkhtmltox_${WKTHMLTOPDF_VERSION}.${WKTHMLTOPDF_DISTRO_VERSION}_amd64.deb
COPY ./wkhtmltox/${WKHTMLTOPDX_FILE} /tmp/$WKHTMLTOPDX_FILE
RUN apt-get update && apt-get install -y wget xfonts-base xfonts-75dpi libxrender1 fontconfig \
    && dpkg -i /tmp/${WKHTMLTOPDX_FILE} \
    && apt-get -f install -y

# Copia os arquivos de configuração
COPY ./nginx/nginx-site.conf /etc/nginx/sites-available/default
COPY ./nginx/supervisord-nginx.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./nginx/zz-custom.conf /usr/local/etc/php-fpm.d/zz-custom.conf
COPY ./nginx/custom-xdebug.ini /usr/local/etc/php/conf.d/custom-xdebug.ini
COPY ./nginx/custom-php.ini /usr/local/etc/php/conf.d/custom-php.ini

# Criar o diretório para o socket e definir as permissões adequadas
RUN mkdir -p /var/run/php/ && chown www-data:www-data /var/run/php/

EXPOSE 80

#CMD ["nginx", "-g", "daemon off;"]
CMD ["/usr/bin/supervisord"]

#### REMOVER
RUN apt-get update && apt-get install -y procps
