# .docker/Dockerfile-apache
FROM php:8.2-apache-bullseye

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=America/Sao_Paulo

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Instalação de dependências e extensões do PHP
RUN apt-get update && apt-get install -y \
    gnupg \
    curl \
    ca-certificates \
    zip \
    unzip \
    git \
    supervisor \
    sqlite3 \
    libpng-dev \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libxml2-dev \
    libxrender1 \
    default-mysql-client \
    apache2 \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql zip bcmath soap intl exif \
    && pecl install redis xdebug \
    && docker-php-ext-enable redis xdebug

# Instalação do Node.js v20 e Puppeteer
RUN apt-get update && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs \
    && npm install puppeteer --global
RUN apt-get update && apt-get install -y chromium

# Instalação do Composer
RUN curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# wkhtmltopdf (mesmo que antes)
# wkhtmltopdf
ENV WKTHMLTOPDF_DISTRO_VERSION bullseye
ENV WKTHMLTOPDF_VERSION 0.12.6.1-2
ENV WKHTMLTOPDX_FILE wkhtmltox_${WKTHMLTOPDF_VERSION}.${WKTHMLTOPDF_DISTRO_VERSION}_amd64.deb
COPY .docker/wkhtmltox/${WKHTMLTOPDX_FILE} /tmp/$WKHTMLTOPDX_FILE
RUN apt-get update && apt-get install -y wget
RUN apt-get update && apt-get install -y xfonts-base
RUN apt-get update && apt-get install -y xfonts-75dpi
RUN apt-get update && apt-get install -y libxrender1
RUN apt-get update && apt-get install -y fontconfig
RUN dpkg -i /tmp/$WKHTMLTOPDX_FILE && apt-get -f install -y

# Copia os arquivos de configuração
COPY .docker/apache/php.ini /usr/local/etc/php/conf.d/99-custom.ini
COPY .docker/apache/000-default.conf /etc/apache2/sites-available/000-default.conf

# Ativa os módulos do Apache
RUN a2enmod rewrite proxy_fcgi headers

EXPOSE 80

## DESCOMENTAR PARA DEPLOY EM PRODUÇÃO!!!
COPY ./ /var/www/html
RUN chown -R www-data:www-data /var/www/html
#RUN composer install --no-dev --optimize-autoloader --no-interaction
#RUN npm install --production
RUN composer install --optimize-autoloader --no-interaction
RUN npm install
RUN npm run build

CMD ["apache2-foreground"]
